CREATE ROLE deku_app WITH LOGIN PASSWORD 'deku-app-pw-2026';
GRANT CONNECT ON DATABASE ethara TO deku_app;
GRANT USAGE, CREATE ON SCHEMA public TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO deku_app;
