CREATE ROLE deku_app LOGIN PASSWORD 'deku-local-dev';
GRANT CONNECT ON DATABASE vvvivid TO deku_app;
GRANT USAGE, CREATE ON SCHEMA public TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO deku_app;
