FROM deku-verifier-base
COPY workflows.yaml /tests/workflows.yaml
COPY rubric.json /tests/rubric.json
COPY conftest.py /tests/conftest.py
COPY test_pytest.py /tests/test_pytest.py
COPY test.sh /tests/test.sh
