CREATE ROLE deku_app WITH LOGIN PASSWORD 'deku-local-dev';
GRANT ALL PRIVILEGES ON DATABASE deku TO deku_app;
\connect deku
GRANT ALL ON SCHEMA public TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO deku_app;
