CREATE ROLE deku_app LOGIN PASSWORD 'deku-local-dev';
GRANT CONNECT ON DATABASE deku TO deku_app;
GRANT ALL ON SCHEMA public TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO deku_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO deku_app;
