CREATE ROLE volari_app WITH LOGIN PASSWORD 'vs-app-pw-2026';
GRANT CONNECT ON DATABASE volari_shop TO volari_app;
GRANT USAGE, CREATE ON SCHEMA public TO volari_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO volari_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO volari_app;
